# Generated by Django 2.2.5 on 2019-09-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SomeNames',
            new_name='Person',
        ),
    ]
