# Generated by Django 2.2.5 on 2019-09-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0002_auto_20190919_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
