# Generated by Django 2.2.5 on 2019-09-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0003_auto_20190919_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Names',
        ),
    ]
